version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: local-postgres
    restart: always
    environment:
      POSTGRES_USER: default
      POSTGRES_PASSWORD: pg-password
      POSTGRES_DB: time-machine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
